

#' Title
#'
#' @param road_raster A raster generated by one of the road algorithms
#' @param num_villages An integer for number of villages that are going to be placed
#'
#' @return
#' @export
#'
#' @examples
placerandomvillage<-function(road_raster,num_villages){

  #start matrix the size of the road raster
  village_matrix <- matrix(0, nrow = nrow(road_raster), ncol = ncol(road_raster))

  #turn road raster into df
  roads_df<-as.data.frame(road_raster, xy=TRUE)

  #give a set of location along a road the value of a village center
  subdf<-roads_df[ sample( which( roads_df$layer == 1 ) , num_villages ) , ]

  for(i in 1:nrow(subdf)){
    village_matrix[subdf$y[i] - 1 ,subdf$x[i] - 1] <- 1

  }

  #add spots on random places acroos the raod
  return(village_matrix)
}
